# Generated by Django 2.1 on 2019-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crimeCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('arrest_count', models.IntegerField()),
            ],
            options={
                'ordering': ['arrest_count'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=2)),
                ('arrest_count', models.IntegerField()),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
