# Generated by Django 2.1 on 2019-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=3)),
                ('team_preffered_name', models.CharField(max_length=25)),
                ('team_name', models.CharField(max_length=25)),
                ('team_city', models.CharField(max_length=25)),
                ('team_conference', models.CharField(max_length=5)),
                ('team_conference_division', models.CharField(max_length=15)),
                ('team_logo_id', models.IntegerField()),
                ('arrest_count', models.IntegerField()),
            ],
        ),
    ]
