# Generated by Django 2.1 on 2019-02-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190211_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'ordering': ['Name']},
        ),
        migrations.RemoveField(
            model_name='details',
            name='team_logo_id',
        ),
    ]
