# Generated by Django 2.1 on 2019-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190211_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='season',
            field=models.CharField(max_length=4),
        ),
    ]
