# Generated by Django 2.1 on 2019-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190211_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='day_of_week_int',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='details',
            name='month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='details',
            name='year',
            field=models.CharField(max_length=12),
        ),
    ]
