# Generated by Django 2.1 on 2019-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190211_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Team_hex_color',
            new_name='team_hex_color',
        ),
    ]
